FROM node:18.12.1-alpine3.16 as builder

# #set the working directory
WORKDIR /app

# # install app dependencies
COPY package.json /app
COPY package-lock.json /app

# #clean install dependecies
RUN npm install

# # add app
COPY . /app

#migrate prisma models
RUN npx prisma generate

# #build backend app
RUN npx nx run api:build:production

# # expose port 8000 to outer environment
EXPOSE 8080

# run app
WORKDIR /app/dist/apps/api
CMD ["node", "main.js"]
